Controllers/ProductCategoryController.cs
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using my_online_shop.Migrations.Data;
using my_online_shop.Models;

namespace my_online_shop.Controllers
{
    public class ProductCategoryController : Controller
    {
        private readonly PostgresDbContext _db;


        public ProductCategoryController(PostgresDbContext db) => _db = db;

        public IActionResult Index()
        {
            var category = _db.ProductCategories.ToList();

            foreach (var c in category)
            {
                _db.Entry(c).Collection(c=>c.Products)
                    .Query()
                    .Where(m=>m.IsAvailable)
                    .Load();

                var products = c.Products;
            }

            return View(_db.ProductCategories);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductCategory productCategory)
        {
            if(!ModelState.IsValid)
                return View();


            _db.Add(productCategory);
            //TempData["isCreated"] = await _db.SaveChangesAsync() > 0;
            await _db.SaveChangesAsync();

            TempData["crudMessage"] = "Product Category has been Created Successfully!";

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Show(int? id)
        {
            var productCategory = _db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return NotFound();
            }

            return View(productCategory);
        }

        [HttpGet]
        public IActionResult Update(int? id)
        {
            var productCategory = _db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return NotFound();
            }

            return View(productCategory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(ProductCategory productCategory)
        {
            if (!ModelState.IsValid)
                return View();


            _db.Update(productCategory);
            await _db.SaveChangesAsync();

            TempData["crudMessage"] = "Product Category has been Updated Successfully!";

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int? id)
        {
            var productCategory = _db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return NotFound();
            }

            _db.ProductCategories.Remove(productCategory);
            _db.SaveChanges();

            TempData["crudMessage"] = "Product Category has been Deleted Successfully!";

            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProductController.cs
using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using my_online_shop.Migrations.Data;
using my_online_shop.Models;

namespace my_online_shop.Controllers
{
    public class ProductController : Controller
    {
        private readonly PostgresDbContext _db;
        private readonly IHostEnvironment _host;

        public ProductController(PostgresDbContext db, IHostEnvironment host)
        {
            _db = db;
            _host = host;
        }

        public IActionResult Index()
        {
            var products = _db.Products.
                Include(p => p.Category).
                Include(p=> p.Tag);
            
            return View(products);
        } 

        [HttpGet]
        public IActionResult Create()
        {
            ViewData["ProductCategories"] = new SelectList(_db.ProductCategories, "Id", "Category");
            ViewData["SpecialTags"] = new SelectList(_db.SpecialTags, "Id", "Tag");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product)
        {
            if(!ModelState.IsValid)
                return View();

            if (product.ImageFile != null)
            {
                var imagePath = Path.Combine($"{_host.ContentRootPath}/wwwroot/images", product.ImageFile.FileName);
                await product.ImageFile.CopyToAsync(new FileStream(imagePath,FileMode.Create));
                
                product.Image = product.ImageFile.FileName;
            }

            _db.Add(product);
            await _db.SaveChangesAsync();

            TempData["crudMessage"] = "Product has been Created Successfully!";

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Show(int? id)
        {
            var product = _db.Products.Find(id);
            if (product == null)
            {
                return NotFound();
            }

            ViewData["ProductCategories"] = new SelectList(_db.ProductCategories, "Id", "Category");
            ViewData["SpecialTags"] = new SelectList(_db.SpecialTags, "Id", "Tag");

            return View(product);
        }

        [HttpGet]
        public IActionResult Update(int? id)
        {
            var product = _db.Products.Find(id);
            if (product == null)
            {
                return NotFound();
            }


            ViewData["ProductCategories"] = new SelectList(_db.ProductCategories, "Id", "Category");
            ViewData["SpecialTags"] = new SelectList(_db.SpecialTags, "Id", "Tag");

            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(Product product)
        {
            if (!ModelState.IsValid)
                return View();

            if (product.ImageFile != null)
            {
                var imagePath = Path.Combine($"{_host.ContentRootPath}/wwwroot/images", product.ImageFile.FileName);
                await product.ImageFile.CopyToAsync(new FileStream(imagePath, FileMode.Create));

                product.Image = product.ImageFile.FileName;
            }

             
            _db.Update(product);
            await _db.SaveChangesAsync();

            TempData["crudMessage"] = "Product has been Updated Successfully!";

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int? id)
        {
            var product = _db.Products.Find(id);
            if (product == null)
            {
                return NotFound();
            }

            _db.Products.Remove(product);
            _db.SaveChanges();

            TempData["crudMessage"] = "Product has been Deleted Successfully!";

            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SpecialTagController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using my_online_shop.Migrations.Data;
using my_online_shop.Models;

namespace my_online_shop.Controllers
{
    public class SpecialTagController : Controller
    {
        private readonly PostgresDbContext _db;


        public SpecialTagController(PostgresDbContext db) => _db = db;

        public IActionResult Index()
        {
            return View(_db.SpecialTags);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SpecialTag specialTag)
        {
            if(!ModelState.IsValid)
                return View();


            _db.Add(specialTag);
            await _db.SaveChangesAsync();

            TempData["crudMessage"] = "Special Tag has been Created Successfully!";

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Show(int? id)
        {
            var specialTag = _db.SpecialTags.Find(id);
            if (specialTag == null)
            {
                return NotFound();
            }

            return View(specialTag);
        }

        [HttpGet]
        public IActionResult Update(int? id)
        {
            var specialTag = _db.SpecialTags.Find(id);
            if (specialTag == null)
            {
                return NotFound();
            }

            return View(specialTag);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(SpecialTag specialTag)
        {
            if (!ModelState.IsValid)
                return View();


            _db.Update(specialTag);
            await _db.SaveChangesAsync();

            TempData["crudMessage"] = "Special Tag has been Updated Successfully!";

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int? id)
        {
            var specialTag = _db.SpecialTags.Find(id);
            if (specialTag == null)
            {
                return NotFound();
            }

            _db.SpecialTags.Remove(specialTag);
            _db.SaveChanges();

            TempData["crudMessage"] = "Special Tag has been Deleted Successfully!";

            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Shared/_ButtonPartial.cshtml
@model dynamic

<div class="">
    
    <a title="Show" asp-action="Show" asp-controller="@ViewData["CrudController"]"
       asp-route-id="@Model" class="btn btn-outline-info">
        <i class="fas fa-list"> </i>
    </a>

    <a title="Update" asp-action="Update" asp-controller="@ViewData["CrudController"]"
       asp-route-id="@Model" class="btn btn-outline-primary">
        <i class="fas fa-edit"> </i>
    </a>

    <a title="Delete" asp-action="Delete" asp-controller="@ViewData["CrudController"]"
       asp-route-id="@Model" class="btn btn-outline-danger">
        <i class="fas fa-trash-alt"> </i>
    </a>
</div>

Views/Shared/_CartPartial.cshtml
@using Microsoft.AspNetCore.Http
@using my_online_shop.Models
@using Newtonsoft.Json
@inject IHttpContextAccessor HttpContextAccessor

@{
    var count = 0;
    var products = HttpContextAccessor.HttpContext?.Session.GetString("SessionProducts") == null ? new List<Product>() 
        : JsonConvert.DeserializeObject<List<Product>>(HttpContextAccessor.HttpContext.Session.GetString("SessionProducts"));

    count = products.Count;
}

<span>@count</span>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyOnlineShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/fontawesome/dist/css/all.css" rel="stylesheet" />
    <link href="~/lib/toastr/dist/toastr.min.css" rel="stylesheet" />
    <link href="~/lib/DataTables/_Combined/datatables.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand"  asp-controller="Home" asp-action="Index">MyOnlineShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="SpecialTag" asp-action="Index">Special-Tag</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="ProductCategory" asp-action="Index">Product-Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Home" asp-action="MyCart">
                                <i class="fas fa-shopping-cart"></i>
                                (<partial name="_CartPartial" /> )
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MyOnlineShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/toastr/dist/toastr.min.js"></script>
    <script src="~/lib/DataTables/_Combined/datatables.min.js"></script>
   
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>